print("Welcome, this program is built by ABIODUN LEKAN")
print("This program functions as a Calculator")
print("How much did you spend on Transport?") 
Transport = int(input())
print("How much did you spend on Feeding?") 
Feeding = int(input())
print("How much did you spend on Miscellaneous?") 
Miscellaneous = int(input())
print("How much did you spend on Water?")
Water = int(input())
print("How much did you spend on Subscription?")
Subscription = int(input())
Sum = (Transport + Feeding + Miscellaneous + Water + Subscription)
print("Opps you have spent the Total of;",str(Sum))
print("How much is your Allowance?")
Allowance = int(input())
Bal = (Allowance - Sum)
print("You have",str(Bal),"Naira left")
print("Thanks For Using This Program")
print("FOR LINAR INSTITUTION")