print("Lekan">"Amara"and"Amara"<"Emma")
print("Amara">"Lekan"and"Lekan">"Emma")
print(3==3 or 4==4)
print("3"=="3" or "4"=="5")
print(20/3)
print(20//3)
print(20%3)
print(4*4+7) 
weight = int(input())
height = int(input())
print(weight*height)
Width = float(input())
Breath = float(input())
print(Width+Breath)
Num = float(input())
Nume = float(input())
print(round(Num))
prefix = 'py'
print(3*'mumu' + 'Segun')
print(prefix + 'thon')
