print("Hello User")
print("What is your name?")
Name = str(input())
print("Can I address you by your name?")
str(input())
print("It is nice meeting you",str(Name))
print("This is a safe spot for you to express yourself")
print("You can talk to me am your friend")
print("How are you doing?")
print("If not good why?")
str(input())
print("How was your day?")
print("Tell me about it I will love hear it")
str(input())
print("mumu Segun")